# Generated by Django 5.2.4 on 2025-07-13 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaceboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='room_id',
        ),
        #migrations.AddField(
         #   model_name='booking',
          #  name='id',
           # field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        #),
        migrations.AddField(
            model_name='room',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
