# Generated by Django 5.2.4 on 2025-07-13 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaceboard', '0002_remove_booking_booking_id_remove_room_room_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='user_name',
            field=models.IntegerField(),
        ),
    ]
