# Generated by Django 5.2.4 on 2025-07-13 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spaceboard', '0004_alter_booking_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='user_name',
            new_name='user_id',
        ),
    ]
