# Generated by Django 5.2.4 on 2025-07-13 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spaceboard', '0005_rename_user_name_booking_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='time_end',
            new_name='end_time',
        ),
    ]
