# Generated by Django 5.2.4 on 2025-07-13 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spaceboard', '0006_rename_time_end_booking_end_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='time_start',
            new_name='start_time',
        ),
    ]
