# Generated by Django 5.2.4 on 2025-07-25 17:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaceboard', '0008_alter_room_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='start_time',
        ),
        migrations.AddField(
            model_name='booking',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 25, 17, 40, 25, 214064, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 25, 18, 42, 2, 617669, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
